import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import {
  ArrowLeft, ArrowRight, BedDouble, Building2, Check, ChevronRight, Compass,
  Facebook, Headphones, Heart, Hotel, Instagram, Map, MapPin, Menu, Mountain,
  Palmtree, Plane, ShieldCheck, Sparkles, Star, Umbrella, Users, X, Youtube,
} from "lucide-react";
import { z } from "zod";
import airplane from "@/assets/airplane.png";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { destinations, experiences, gallery, heroSlides, packages, testimonials, type DestinationCategory } from "@/data/travel";
import { cn } from "@/lib/utils";

const WHATSAPP_NUMBER = "[WHATSAPP_NUMBER]";
const nav = [
  ["Home", "#home"], ["Destinations", "#destinations"], ["Travel Experiences", "#experiences"],
  ["Packages", "#packages"], ["About Us", "#about"], ["Reviews", "#reviews"], ["Contact", "#enquiry"],
] as const;
const categories: { key: DestinationCategory; label: string }[] = [
  { key: "popular", label: "Popular Destinations" }, { key: "india", label: "Indian Destinations" }, { key: "visa-free", label: "Visa Information" },
];
const requirements = ["Flight", "Hotel", "Cab", "Sightseeing", "Activities", "Visa Assistance", "Travel Insurance"];
const tripTypes = ["Honeymoon", "Family", "Couple", "Friends", "Solo", "Group", "Corporate", "Adventure", "Luxury", "Other"];
const budgets = ["Under ₹50,000", "₹50,000 – ₹1 Lakh", "₹1 Lakh – ₹2 Lakhs", "₹2 Lakhs – ₹5 Lakhs", "₹5 Lakhs+", "Flexible / Need guidance"];

const enquirySchema = z.object({
  name: z.string().trim().min(1, "Please enter your name.").max(100),
  phone: z.string().trim().regex(/^(?:\+91[\s-]?)?[6-9]\d{9}$/, "Please enter a valid Indian WhatsApp number."),
  email: z.string().trim().email("Please enter a valid email address.").max(255).or(z.literal("")),
  destination: z.string().trim().min(1, "Please select your destination."),
  travelDate: z.string().min(1, "Please select your travel date."),
  returnDate: z.string(), days: z.string(), adults: z.coerce.number().min(1, "At least one adult is required."),
  children: z.coerce.number().min(0), infants: z.coerce.number().min(0), tripType: z.string(), budget: z.string(), notes: z.string().max(1000),
}).refine((value) => !value.returnDate || value.returnDate >= value.travelDate, { path: ["returnDate"], message: "Return date must be after the travel date." });

type FormErrors = Record<string, string | undefined>;

function Brand({ light = false }: { light?: boolean }) {
  return <a href="#home" className={cn("group inline-flex items-center gap-3", light ? "text-cream" : "text-foreground")} aria-label="Happy Hearts Holidays home">
    <span className="grid size-10 place-items-center rounded-full border border-current/20 bg-primary text-primary-foreground shadow-soft"><Heart className="size-5 fill-current" /></span>
    <span className="leading-none"><strong className="block font-display text-[1.08rem] font-semibold">Happy Hearts</strong><span className="mt-1 block text-[0.62rem] font-bold uppercase tracking-[0.22em] text-gold">Holidays</span></span>
  </a>;
}

function ArrowLink({ href, children, variant = "primary", className }: { href: string; children: React.ReactNode; variant?: "primary" | "outline" | "light" | "whatsapp"; className?: string }) {
  return <Button asChild size="lg" variant={variant === "outline" ? "outline" : "default"} className={cn("group h-12 rounded-full px-6 transition-all duration-300 hover:-translate-y-0.5", variant === "light" && "border border-cream/40 bg-cream/10 text-cream hover:bg-cream hover:text-foreground", variant === "whatsapp" && "bg-whatsapp text-whatsapp-foreground hover:bg-whatsapp/90", className)}>
    <a href={href}>{children}<ArrowRight className="transition-transform duration-300 group-hover:translate-x-1" /></a>
  </Button>;
}

function Header() {
  const [scrolled, setScrolled] = useState(false); const [open, setOpen] = useState(false);
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 30); onScroll(); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, []);
  return <header className={cn("fixed inset-x-0 top-0 z-50 transition-all duration-500", scrolled ? "border-b border-border/60 bg-background/95 py-2 shadow-soft backdrop-blur-xl" : "bg-transparent py-4 text-cream")}>
    <div className="page-container flex items-center justify-between"><Brand light={!scrolled} />
      <nav className="hidden items-center gap-5 xl:flex" aria-label="Primary navigation">{nav.map(([label, href]) => <a key={href} href={href} className="nav-link text-xs font-semibold">{label}</a>)}</nav>
      <div className="flex items-center gap-2"><ArrowLink href="#enquiry" className="hidden h-10 px-5 sm:inline-flex">Plan My Trip</ArrowLink><Button size="icon" variant="ghost" className="xl:hidden" aria-label="Open menu" onClick={() => setOpen(true)}><Menu /></Button></div>
    </div>
    {open && <div className="fixed inset-0 z-50 bg-background p-6 text-foreground xl:hidden"><div className="flex items-center justify-between"><Brand /><Button size="icon" variant="ghost" aria-label="Close menu" onClick={() => setOpen(false)}><X /></Button></div><nav className="mt-14 flex flex-col" aria-label="Mobile navigation">{nav.map(([label, href]) => <a key={href} href={href} onClick={() => setOpen(false)} className="border-b border-border py-5 font-display text-2xl">{label}</a>)}</nav><ArrowLink href="#enquiry" className="mt-8 w-full" >Plan My Trip</ArrowLink></div>}
  </header>;
}

function Hero() {
  const [slide, setSlide] = useState(0); const [paused, setPaused] = useState(false); const touch = useRef(0);
  useEffect(() => { if (paused) return; const id = window.setInterval(() => setSlide((s) => (s + 1) % heroSlides.length), 6000); return () => window.clearInterval(id); }, [paused]);
  const move = (direction: number) => setSlide((s) => (s + direction + heroSlides.length) % heroSlides.length);
  return <section id="home" className="relative min-h-[760px] overflow-hidden bg-foreground text-cream sm:min-h-[800px] lg:h-[92vh] lg:min-h-[760px]" onMouseEnter={() => setPaused(true)} onMouseLeave={() => setPaused(false)} onTouchStart={(e) => { touch.current = e.touches[0]?.clientX ?? 0; }} onTouchEnd={(e) => { const delta = (e.changedTouches[0]?.clientX ?? 0) - touch.current; if (Math.abs(delta) > 45) move(delta > 0 ? -1 : 1); }}>
    {heroSlides.map((item, index) => <img key={item.quote} src={item.image} alt={`${item.location} travel landscape`} width={1536} height={1024} fetchPriority={index === 0 ? "high" : "auto"} className={cn("absolute inset-0 h-full w-full object-cover transition-[opacity,transform] duration-1000", slide === index ? "scale-100 opacity-100" : "scale-[1.04] opacity-0")} />)}
    <div className="absolute inset-0 bg-hero-overlay" />
    <div className="air-route" aria-hidden="true"><span className="route-line"/><img src={airplane} alt="" width={1152} height={576} className="airplane" /></div>
    <div className="page-container relative z-10 flex min-h-[760px] items-end pb-28 pt-32 sm:min-h-[800px] lg:h-[92vh] lg:min-h-[760px] lg:items-center lg:pb-12">
      <div className="max-w-3xl animate-fade-in" key={slide}><p className="eyebrow text-gold">Welcome to Happy Hearts Holidays</p><h1 className="mt-5 max-w-3xl font-display text-5xl leading-[1.02] sm:text-6xl lg:text-7xl">Your Journey.<br/>Your Memories. <em className="font-normal text-gold">Your Way.</em></h1><blockquote className="mt-7 font-display text-xl italic text-cream/95 sm:text-2xl">“{heroSlides[slide].quote}”</blockquote><p className="mt-4 max-w-2xl text-base leading-7 text-cream/80 sm:text-lg">{heroSlides[slide].description}</p><div className="mt-8 flex flex-wrap gap-3"><ArrowLink href={heroSlides[slide].href}>{heroSlides[slide].cta}</ArrowLink><ArrowLink href="#destinations" variant="light">Explore Destinations</ArrowLink><ArrowLink href="#enquiry" variant="whatsapp">Chat on WhatsApp</ArrowLink></div></div>
    </div>
    <div className="absolute bottom-7 left-1/2 z-20 flex w-[calc(100%-2rem)] -translate-x-1/2 items-center justify-between sm:w-auto sm:gap-5"><Button variant="ghost" size="icon" onClick={() => move(-1)} className="rounded-full border border-cream/30 text-cream hover:bg-cream/10" aria-label="Previous hero slide"><ArrowLeft /></Button><div className="flex gap-2">{heroSlides.map((_, i) => <Button key={i} variant="ghost" aria-label={`Show slide ${i + 1}`} onClick={() => setSlide(i)} className={cn("h-1 min-w-0 rounded-full p-0 transition-all", i === slide ? "w-10 bg-gold" : "w-5 bg-cream/50")} />)}</div><Button variant="ghost" size="icon" onClick={() => move(1)} className="rounded-full border border-cream/30 text-cream hover:bg-cream/10" aria-label="Next hero slide"><ArrowRight /></Button></div>
  </section>;
}

const trustItems = [
  [Sparkles, "Personalized Trips", "Tailored to your interests"], [Headphones, "Trusted Travel Support", "We're with you throughout"], [Compass, "Handpicked Experiences", "The best for your holiday"], [ShieldCheck, "End-to-End Assistance", "From planning to your return"],
] as const;
function TrustBar() { return <section className="border-b border-border bg-background"><div className="page-container grid grid-cols-2 gap-px bg-border lg:grid-cols-4">{trustItems.map(([Icon, title, text]) => <div key={title} className="flex gap-3 bg-background px-3 py-6 sm:px-6"><Icon className="mt-0.5 size-6 shrink-0 text-primary"/><div><h2 className="text-sm font-bold">{title}</h2><p className="mt-1 text-xs text-muted-foreground">{text}</p></div></div>)}</div></section>; }

function SectionHeading({ eyebrow, title, copy, align = "center" }: { eyebrow?: string; title: string; copy?: string; align?: "center" | "left" }) { return <div className={cn("mb-10", align === "center" ? "mx-auto max-w-2xl text-center" : "max-w-2xl")}><p className="eyebrow text-primary">{eyebrow}</p><h2 className="mt-3 font-display text-4xl leading-tight sm:text-5xl">{title}</h2>{copy && <p className="mt-4 leading-7 text-muted-foreground">{copy}</p>}</div>; }

function DestinationCard({ item, compact = false }: { item: (typeof destinations)[number]; compact?: boolean }) { return <article className="destination-card group relative min-w-0 overflow-hidden rounded-card bg-card shadow-card"><div className={cn("overflow-hidden", compact ? "aspect-[4/3]" : "aspect-[4/5]")}><img loading="lazy" src={item.image} alt={`${item.name}, ${item.country}`} width={1536} height={1024} className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-card-overlay"/></div><div className="absolute inset-x-0 bottom-0 p-5 text-cream"><p className="text-xs font-bold uppercase tracking-[0.16em] text-gold">{item.country}</p><h3 className="mt-1 font-display text-3xl">{item.name}</h3><p className="mt-2 line-clamp-2 text-sm text-cream/80">{item.description}</p><a href="#enquiry" className="mt-4 inline-flex items-center gap-2 text-sm font-bold">Explore trip <ArrowRight className="size-4 transition-transform group-hover:translate-x-1"/></a></div></article>; }

function TravelYourWay() {
  const [category, setCategory] = useState<DestinationCategory>("popular");
  const items = destinations.filter((d) => d.category.includes(category)).slice(0, 6);
  return <section id="destinations" className="section-space bg-surface"><div className="page-container"><SectionHeading eyebrow="Discover" title="TRAVEL YOUR WAY" copy="Every remarkable holiday starts with a feeling. Find the places that match yours."/><div className="mb-9 flex snap-x gap-2 overflow-x-auto pb-2 sm:justify-center" role="tablist">{categories.map((item) => <Button key={item.key} role="tab" aria-selected={category === item.key} onClick={() => setCategory(item.key)} variant={category === item.key ? "default" : "outline"} className="h-11 shrink-0 rounded-full px-5">{item.label}</Button>)}</div><div key={category} className="grid animate-fade-in grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">{items.map((item) => <DestinationCard key={item.id} item={item}/>)}</div>{category === "visa-free" && <p className="mt-6 text-center text-sm text-muted-foreground">Visa information is available on enquiry and may change. Our team will help you check current requirements.</p>}</div></section>;
}

function TopPicks() { return <section className="section-space"><div className="page-container"><SectionHeading eyebrow="Chosen with care" title="OUR TOP PICKS" copy="Handpicked journeys for unforgettable moments"/><div className="flex snap-x gap-5 overflow-x-auto pb-5 lg:grid lg:grid-cols-4 lg:overflow-visible">{packages.map((item) => <div key={item.id} className="w-[82vw] shrink-0 snap-center sm:w-[44vw] lg:w-auto"><DestinationCard item={item} compact/></div>)}</div></div></section>; }
function MostPopular() { const [featured, ...small] = destinations.filter((d) => ["kashmir","dubai","maldives","bali","goa"].includes(d.id)); return <section className="section-space bg-foreground text-cream"><div className="page-container"><SectionHeading eyebrow="Travelers' favorites" title="MOST POPULAR DESTINATIONS" align="left"/><div className="grid gap-5 lg:grid-cols-2"><div className="lg:row-span-2"><DestinationCard item={featured} /></div><div className="grid grid-cols-2 gap-4">{small.map((item) => <DestinationCard key={item.id} item={item} compact/>)}</div></div></div></section>; }

function Curated() { return <section className="section-space overflow-hidden"><div className="page-container grid items-center gap-10 lg:grid-cols-[43%_57%]"><div className="image-reveal aspect-[4/3] overflow-hidden rounded-card"><img loading="lazy" src={heroSlides[1].image} alt="Private overwater stay in the Maldives" width={1536} height={1024} className="h-full w-full object-cover transition-transform duration-1000 hover:scale-105"/></div><div className="lg:pl-10"><SectionHeading eyebrow="Created around you" title="CURATED FOR YOU" copy="Unique experiences, handpicked just for you." align="left"/><p className="max-w-xl leading-8 text-muted-foreground">Not a package pulled from a shelf. We shape stays, pacing and experiences around how you want your holiday to feel—from slow mornings by the sea to immersive days in the mountains.</p><ArrowLink href="#enquiry" className="mt-7">Plan My Journey</ArrowLink></div></div></section>; }
function Experiences() { return <section id="experiences" className="section-space bg-surface"><div className="page-container"><SectionHeading eyebrow="Find your feeling" title="TRAVEL EXPERIENCES" copy="Choose your kind of escape"/><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{experiences.map((item) => <article key={item.title} className="group relative aspect-[4/3] overflow-hidden rounded-card"><img loading="lazy" src={item.image} alt={item.title} width={1536} height={1024} className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-card-overlay"/><div className="absolute inset-x-0 bottom-0 p-6 text-cream"><div className="flex items-end justify-between gap-4"><div><h3 className="font-display text-2xl">{item.title}</h3><p className="mt-2 text-sm leading-6 text-cream/80">{item.text}</p></div><ArrowRight className="shrink-0 transition-transform group-hover:translate-x-1"/></div></div></article>)}</div></div></section>; }
function StorySection() { return <section id="about" className="section-space"><div className="page-container grid items-center gap-10 lg:grid-cols-[42%_58%]"><div className="aspect-[4/3] overflow-hidden rounded-card"><img loading="lazy" src={heroSlides[0].image} alt="Thoughtfully planned Kashmir journey" width={1536} height={1024} className="h-full w-full object-cover"/></div><div className="lg:pl-12"><SectionHeading eyebrow="Happy Hearts Holidays" title="THE HEART BEHIND THE JOURNEY" copy="More than a trip. It's your story." align="left"/><p className="max-w-2xl text-lg leading-8 text-muted-foreground">At Happy Hearts Holidays, we believe every journey should be personal. We take the time to understand what you want from your holiday and help create an experience that feels uniquely yours.</p><ArrowLink href="#enquiry" className="mt-8">Plan My Journey</ArrowLink></div></div></section>; }

function Testimonials() {
  const [active, setActive] = useState(0); const [pause, setPause] = useState(false);
  useEffect(() => { if (pause) return; const id = window.setInterval(() => setActive((i) => (i + 1) % testimonials.length), 5500); return () => clearInterval(id); }, [pause]);
  return <section id="reviews" className="section-space bg-accent"><div className="page-container"><SectionHeading eyebrow="Sample stories" title="STORIES FROM HAPPY TRAVELERS" copy="Moments that made the journey unforgettable"/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3" onMouseEnter={() => setPause(true)} onMouseLeave={() => setPause(false)}>{testimonials.map((item, i) => <article key={item.name} className={cn("rounded-card border bg-background p-6 transition-all duration-500", active === i ? "border-primary shadow-card" : "border-border")}><div className="flex items-center justify-between gap-3"><span className="text-xs font-bold uppercase tracking-[0.14em] text-primary">Sample traveler story</span><div className="flex" aria-label="5 out of 5 stars">{Array.from({length:5}).map((_,j)=><Star key={j} className="size-4 fill-gold text-gold"/>)}</div></div><blockquote className="mt-6 font-display text-xl leading-8">“{item.story}”</blockquote><div className="mt-7 border-t border-border pt-5"><p className="font-bold">{item.name}</p><p className="text-sm text-muted-foreground">{item.destination} · {item.type}</p></div></article>)}</div><div className="mt-8 flex items-center justify-center gap-3"><Button size="icon" variant="outline" className="rounded-full" aria-label="Previous story" onClick={() => {setActive((active - 1 + testimonials.length) % testimonials.length); setPause(true)}}><ArrowLeft/></Button>{testimonials.map((_, i) => <Button key={i} variant="ghost" onClick={() => {setActive(i);setPause(true)}} className={cn("size-2 min-w-0 rounded-full p-0", active === i ? "bg-primary" : "bg-border")} aria-label={`Show story ${i+1}`}/>) }<Button size="icon" variant="outline" className="rounded-full" aria-label="Next story" onClick={() => {setActive((active + 1) % testimonials.length); setPause(true)}}><ArrowRight/></Button></div></div></section>;
}

const moods = [[Mountain,"Mountains",0],[Umbrella,"Beaches",1],[Building2,"Cities",4],[Map,"Culture",2],[Compass,"Adventure",4]] as const;
function MoodStrip() { return <section className="section-space overflow-hidden bg-foreground text-cream"><div className="page-container"><SectionHeading eyebrow="Follow the feeling" title="WHERE WILL YOU GO NEXT?" copy="From mountains to beaches, from cities to culture — the world is waiting."/><div className="flex snap-x gap-4 overflow-x-auto pb-4">{moods.map(([Icon,title,image]) => <a key={title} href="#enquiry" className="group relative h-80 w-[72vw] max-w-xs shrink-0 snap-center overflow-hidden rounded-card sm:w-64"><img loading="lazy" src={heroSlides[image].image} alt={`${title} travel`} width={1536} height={1024} className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-card-overlay"/><div className="absolute inset-x-0 bottom-0 flex items-center gap-3 p-5"><Icon className="text-gold"/><span className="font-display text-2xl">{title}</span></div></a>)}</div></div></section>; }
function Packages() { return <section id="packages" className="section-space"><div className="page-container"><SectionHeading eyebrow="Ideas to begin with" title="POPULAR HOLIDAY PACKAGES" copy="Flexible starting points, personalized around your dates, people and travel style."/><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{packages.slice(0,4).map((item)=><article key={item.id} className="rounded-card border border-border bg-card p-3 shadow-soft"><img loading="lazy" src={item.image} alt={`${item.name} holiday package`} width={1536} height={1024} className="aspect-[4/3] w-full rounded-[calc(var(--radius)-0.15rem)] object-cover"/><div className="p-3"><p className="text-xs font-bold uppercase tracking-[0.14em] text-primary">{item.country}</p><h3 className="mt-1 font-display text-2xl">{item.name}</h3><p className="mt-2 text-sm text-muted-foreground">{item.duration}</p><p className="mt-3 text-sm leading-6 text-muted-foreground">{item.description}</p><a href="#enquiry" className="mt-5 inline-flex items-center gap-2 font-bold text-primary">Get a Quote <ArrowRight className="size-4"/></a></div></article>)}</div></div></section>; }

function Field({ label, required, error, children }: { label: string; required?: boolean; error?: string; children: React.ReactNode }) { return <label className="block text-sm font-semibold"><span>{label}{required && <span className="text-primary"> *</span>}</span><span className="mt-2 block">{children}</span>{error && <span className="mt-1.5 block text-xs text-destructive">{error}</span>}</label>; }
function EnquiryForm() {
  const [errors, setErrors] = useState<FormErrors>({}); const [selected, setSelected] = useState<string[]>([]); const [success, setSuccess] = useState<{url:string; message:string} | null>(null);
  const minDate = useMemo(() => new Date().toISOString().split("T")[0], []);
  function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = new FormData(e.currentTarget); const raw = Object.fromEntries(form.entries()); const parsed = enquirySchema.safeParse(raw); if (!parsed.success) { const next: FormErrors = {}; parsed.error.issues.forEach((issue) => { const key = String(issue.path[0]); if (!next[key]) next[key] = issue.message; }); setErrors(next); setSuccess(null); return; }
    setErrors({}); const d = parsed.data; const travelerBits = [`${d.adults} Adult${d.adults > 1 ? "s" : ""}`]; if (d.children) travelerBits.push(`${d.children} Children`); if (d.infants) travelerBits.push(`${d.infants} Infants`);
    const lines = ["Hi Happy Hearts Holidays! 👋", "", "I would like to plan a trip.", "", `Name: ${d.name}`, `WhatsApp: ${d.phone}`, `Destination: ${d.destination}`, `Travel Date: ${d.travelDate}`, d.returnDate && `Return Date: ${d.returnDate}`, d.days && `Duration: ${d.days} days`, `Travelers: ${travelerBits.join(", ")}`, d.tripType && `Trip Type: ${d.tripType}`, d.budget && `Budget: ${d.budget}`, "", "Requirements:", selected.length ? selected.join(", ") : "Please advise", "", "Additional Requirements:", d.notes || "None specified", "", "Please help me plan my trip."].filter((line) => line !== false);
    const message = lines.join("\n"); const configured = /^\d{10,15}$/.test(WHATSAPP_NUMBER.replace(/\D/g,"")); const base = configured ? `https://wa.me/${WHATSAPP_NUMBER.replace(/\D/g,"")}` : "https://wa.me/"; setSuccess({ message, url: `${base}?text=${encodeURIComponent(message)}` }); window.setTimeout(() => document.getElementById("enquiry-success")?.scrollIntoView({behavior:"smooth",block:"center"}), 50);
  }
  if (success) return <div id="enquiry-success" className="rounded-card bg-background p-6 shadow-card sm:p-10"><span className="grid size-14 place-items-center rounded-full bg-accent text-primary"><Check className="size-7"/></span><h3 className="mt-6 font-display text-4xl">Your Trip Details Are Ready!</h3><p className="mt-3 text-muted-foreground">Continue to WhatsApp to review your enquiry and press Send manually.</p><div className="mt-6 max-h-64 overflow-auto rounded-card border border-border bg-surface p-4"><pre className="whitespace-pre-wrap font-sans text-sm leading-6">{success.message}</pre></div>{WHATSAPP_NUMBER.includes("[") && <p className="mt-4 rounded-md bg-accent p-3 text-sm text-accent-foreground">WhatsApp number is not configured yet. The message is ready; add the business number to enable the final handoff.</p>}<div className="mt-6 flex flex-wrap gap-3"><Button asChild className="h-12 rounded-full bg-whatsapp px-6 text-whatsapp-foreground hover:bg-whatsapp/90"><a href={success.url} target="_blank" rel="noreferrer">Continue to WhatsApp <ArrowRight/></a></Button><Button variant="outline" className="h-12 rounded-full" onClick={()=>setSuccess(null)}>Edit details</Button></div></div>;
  return <form noValidate onSubmit={submit} className="rounded-card bg-background p-5 shadow-card sm:p-9"><fieldset><legend className="font-display text-2xl">Personal details</legend><div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label="Full Name" required error={errors.name}><Input name="name" maxLength={100} placeholder="Your full name" aria-invalid={Boolean(errors.name)} /></Field><Field label="WhatsApp Number" required error={errors.phone}><Input name="phone" type="tel" inputMode="tel" maxLength={14} placeholder="+91 98765 43210" aria-invalid={Boolean(errors.phone)} /></Field><Field label="Email" error={errors.email}><Input name="email" type="email" maxLength={255} placeholder="you@example.com" aria-invalid={Boolean(errors.email)} /></Field></div></fieldset>
    <fieldset className="mt-8 border-t border-border pt-8"><legend className="font-display text-2xl">Trip details</legend><div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label="Destination" required error={errors.destination}><select name="destination" defaultValue="" className="form-control" aria-invalid={Boolean(errors.destination)}><option value="" disabled>Choose a destination</option>{destinations.map((d)=><option key={d.id}>{d.name}</option>)}</select></Field><Field label="Travel Date" required error={errors.travelDate}><Input name="travelDate" type="date" min={minDate} aria-invalid={Boolean(errors.travelDate)} /></Field><Field label="Return Date" error={errors.returnDate}><Input name="returnDate" type="date" min={minDate} aria-invalid={Boolean(errors.returnDate)} /></Field><Field label="Number of Days"><Input name="days" type="number" min="1" max="90" placeholder="6" /></Field></div></fieldset>
    <fieldset className="mt-8 border-t border-border pt-8"><legend className="font-display text-2xl">Travelers</legend><div className="mt-5 grid grid-cols-1 gap-5 sm:grid-cols-3"><Field label="Adults" required error={errors.adults}><Input name="adults" type="number" min="1" max="50" defaultValue="2" /></Field><Field label="Children"><Input name="children" type="number" min="0" max="50" defaultValue="0" /></Field><Field label="Infants"><Input name="infants" type="number" min="0" max="20" defaultValue="0" /></Field><Field label="Trip Type"><select name="tripType" className="form-control"><option value="">Choose trip type</option>{tripTypes.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Budget"><select name="budget" className="form-control"><option value="">Choose a range</option>{budgets.map(x=><option key={x}>{x}</option>)}</select></Field></div></fieldset>
    <fieldset className="mt-8 border-t border-border pt-8"><legend className="font-display text-2xl">Requirements</legend><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{requirements.map(item=><label key={item} className="flex min-h-11 cursor-pointer items-center gap-3 rounded-md border border-border px-3 text-sm"><Checkbox checked={selected.includes(item)} onCheckedChange={(checked)=>setSelected(s=>checked?[...s,item]:s.filter(x=>x!==item))}/>{item}</label>)}</div><Field label="Additional Requirements"><Textarea name="notes" maxLength={1000} className="mt-5 min-h-32" placeholder="Tell us anything else you'd like us to know about your trip." /></Field></fieldset><Button type="submit" size="lg" className="mt-8 h-13 w-full rounded-full sm:w-auto">Prepare My WhatsApp Enquiry <ArrowRight/></Button>
  </form>;
}
function Enquiry() { return <section id="enquiry" className="section-space bg-accent"><div className="page-container grid gap-12 lg:grid-cols-[36%_64%]"><div className="lg:sticky lg:top-28 lg:self-start"><p className="eyebrow text-primary">Let’s plan something beautiful</p><h2 className="mt-3 font-display text-4xl leading-tight sm:text-5xl">TELL US ABOUT YOUR DREAM TRIP</h2><p className="mt-5 leading-7 text-muted-foreground">Share a few details and we'll help you plan the perfect holiday.</p><div className="mt-8 space-y-5">{[[Heart,"Personal to you"],[Hotel,"Stays that fit your style"],[Plane,"Complete travel assistance"]].map(([Icon,text])=><div key={text as string} className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-background text-primary"><Icon className="size-5"/></span><span className="font-semibold">{text as string}</span></div>)}</div></div><EnquiryForm/></div></section>; }

function GalleryAndSteps() { return <><section className="section-space"><div className="page-container"><SectionHeading eyebrow="Travel gallery" title="MOMENTS WORTH REMEMBERING"/><div className="grid auto-rows-[220px] grid-cols-2 gap-3 lg:grid-cols-4">{gallery.map((item,i)=><figure key={item.title} className={cn("group relative overflow-hidden rounded-card", i===0&&"col-span-2 row-span-2")}><img loading="lazy" src={item.image} alt={item.title} width={1536} height={1024} className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-105"/><figcaption className="absolute inset-x-0 bottom-0 bg-card-overlay p-4 pt-16 font-display text-xl text-cream opacity-0 transition-opacity group-hover:opacity-100">{item.title}</figcaption></figure>)}</div></div></section><section className="section-space bg-surface"><div className="page-container"><SectionHeading eyebrow="Simple by design" title="YOUR DREAM TRIP IN 3 SIMPLE STEPS"/><div className="relative grid gap-8 md:grid-cols-3"><div className="absolute left-[16%] right-[16%] top-7 hidden border-t border-dashed border-primary/40 md:block"/>{[["01","Tell Us Your Plan","Share your destination, dates, travelers and budget."],["02","We Create Your Journey","Our travel team prepares a personalized plan around your requirements."],["03","Pack Your Bags","Confirm your trip and get ready for an unforgettable journey."]].map(([number,title,text])=><article key={number} className="relative text-center"><span className="relative z-10 mx-auto grid size-14 place-items-center rounded-full bg-primary font-bold text-primary-foreground">{number}</span><h3 className="mt-5 font-display text-2xl">{title}</h3><p className="mx-auto mt-3 max-w-xs leading-7 text-muted-foreground">{text}</p></article>)}</div></div></section></>; }
function About() { return <section className="section-space"><div className="page-container max-w-4xl text-center"><SectionHeading eyebrow="Our promise" title="ABOUT HAPPY HEARTS HOLIDAYS"/><p className="text-lg leading-8 text-muted-foreground">At Happy Hearts Holidays, we believe every traveler deserves a journey that feels personal. From destination selection to stays, experiences and transportation, we help turn your holiday ideas into memorable journeys.</p><ArrowLink href="#enquiry" className="mt-8">Plan My Journey</ArrowLink></div></section>; }
function FinalCta() { return <section className="relative isolate overflow-hidden py-28 text-cream sm:py-36"><img loading="lazy" src={heroSlides[3].image} alt="Romantic ocean sunset" width={1536} height={1024} className="absolute inset-0 -z-20 h-full w-full object-cover"/><div className="absolute inset-0 -z-10 bg-hero-overlay"/><div className="page-container text-center"><p className="eyebrow text-gold">Your story starts here</p><h2 className="mx-auto mt-4 max-w-3xl font-display text-5xl leading-tight sm:text-6xl">YOUR NEXT ADVENTURE IS WAITING</h2><p className="mx-auto mt-5 max-w-xl text-lg text-cream/80">Tell us where your heart wants to go. We'll help plan the journey.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><ArrowLink href="#enquiry">Plan My Trip</ArrowLink><ArrowLink href="#enquiry" variant="whatsapp">Chat on WhatsApp</ArrowLink></div></div></section>; }
function Footer() { return <footer className="bg-footer py-16 pb-28 text-footer-foreground sm:pb-16"><div className="page-container"><div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-4"><div><Brand light/><p className="mt-5 max-w-xs text-sm leading-6 text-footer-muted">Your Journey. Your Memories. Your Way.</p></div><div><h2 className="footer-title">Quick Links</h2><div className="mt-4 grid gap-2">{nav.map(([label,href])=><a key={href} href={href} className="footer-link">{label}</a>)}</div></div><div><h2 className="footer-title">Services</h2><div className="mt-4 grid gap-2">{["Domestic Holidays","International Holidays","Honeymoon Packages","Family Holidays","Group Travel","Hotel Booking","Flight Assistance","Visa Assistance"].map(x=><span key={x} className="footer-link">{x}</span>)}</div></div><div><h2 className="footer-title">Contact</h2><div className="mt-4 grid gap-2 text-sm text-footer-muted"><span>[PHONE NUMBER]</span><span>[WHATSAPP NUMBER]</span><span>[EMAIL ADDRESS]</span><span>[OFFICE ADDRESS]</span></div><div className="mt-6 flex gap-2">{[[Instagram,"Instagram"],[Facebook,"Facebook"],[Youtube,"YouTube"]].map(([Icon,label])=><Button key={label as string} size="icon" variant="ghost" className="rounded-full border border-footer-foreground/20" aria-label={label as string}><Icon/></Button>)}</div></div></div><div className="mt-12 flex flex-col gap-4 border-t border-footer-foreground/15 pt-6 text-xs text-footer-muted sm:flex-row sm:items-center sm:justify-between"><span>© 2026 Happy Hearts Holidays</span><div className="flex flex-wrap gap-5"><span>Privacy Policy</span><span>Terms & Conditions</span><span>Cancellation Policy</span></div></div></div></footer>; }

export function TravelLandingPage() { return <><Header/><main><Hero/><TrustBar/><TravelYourWay/><TopPicks/><MostPopular/><Curated/><Experiences/><StorySection/><Testimonials/><MoodStrip/><Packages/><Enquiry/><GalleryAndSteps/><About/><FinalCta/></main><Footer/><a href="#enquiry" className="fixed bottom-3 left-1/2 z-40 flex h-12 -translate-x-1/2 items-center gap-2 whitespace-nowrap rounded-full bg-whatsapp px-5 text-sm font-bold text-whatsapp-foreground shadow-card active:scale-[0.98] sm:hidden"><Heart className="size-4 fill-current"/>Plan My Trip on WhatsApp</a></>; }
